dubbo:
  application:
    name: view-facade
  registry:
    address: zookeeper://192.168.140.129:2181
  protocol:
    port: 20881
server:
  port: 9091
#spring:
#  redis:
#    host: 192.168.140.129
#    port: 6379
#    password: qfjava
#    jedis:
#      pool:
#        max-active: 8
spring:
  kafka:
    bootstrap-servers: 192.168.140.129:9092,192.168.140.129:9093,192.168.140.129:9094
    producer: # 生产者
      retries: 3 # 设置大于0的值，则客户端会将发送失败的记录重新发送
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
